public class TUGAS1_21 {
    
    public static void main(String[] args) {
        System.out.println("***IDENTITAS DIRI***");
        System.out.println("Nama       :Saya Nabhan Rizqi Julian Saputro");
        System.out.println("Absen      :21");
        System.out.println("Kelas      :1B");
        System.out.println("Prodi      :Teknik Informatika");
        System.out.println("Jurusan    :Teknologi Informasi");

    }
}